
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Nov 10 2023 15:51:36 IST (Nov 10 2023 10:21:36 UTC)

// Verification Directory fv/weighted_rr 

module weighted_rr(reset, clk, request, weight, grant1);
  input reset, clk;
  input [7:0] request;
  input [255:0] weight;
  output [7:0] grant1;
  wire reset, clk;
  wire [7:0] request;
  wire [255:0] weight;
  wire [7:0] grant1;
  wire [31:0] g1_s_counter;
  wire [31:0] g1_s_weight;
  wire [3:0] g1_state;
  wire [7:0] s_nextGrant;
  wire [1:0] ngpc_state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  wire UNCONNECTED39, UNCONNECTED40, UNCONNECTED41, UNCONNECTED42,
       UNCONNECTED43, UNCONNECTED44, UNCONNECTED45, UNCONNECTED46;
  wire UNCONNECTED47, UNCONNECTED48, UNCONNECTED49, UNCONNECTED50,
       UNCONNECTED51, UNCONNECTED52, UNCONNECTED53, UNCONNECTED54;
  wire UNCONNECTED55, UNCONNECTED56, UNCONNECTED57, UNCONNECTED58,
       UNCONNECTED59, UNCONNECTED60, UNCONNECTED61, UNCONNECTED62;
  wire UNCONNECTED63, UNCONNECTED64, UNCONNECTED65, UNCONNECTED66,
       UNCONNECTED67, UNCONNECTED68, g1_gte_48_14_n_8,
       g1_gte_48_14_n_14;
  wire g1_gte_48_14_n_26, g1_gte_48_14_n_38, g1_gte_48_14_n_40,
       g1_gte_48_14_n_46, g1_gte_48_14_n_62, g1_gte_48_14_n_63,
       g1_gte_48_14_n_64, g1_gte_48_14_n_65;
  wire g1_gte_48_14_n_66, g1_inc_add_89_20_n_221,
       g1_inc_add_89_20_n_224, g1_inc_add_89_20_n_227,
       g1_inc_add_89_20_n_229, g1_inc_add_89_20_n_231,
       g1_inc_add_89_20_n_233, g1_inc_add_89_20_n_235;
  wire g1_inc_add_89_20_n_237, g1_inc_add_89_20_n_239,
       g1_inc_add_89_20_n_241, g1_inc_add_89_20_n_243,
       g1_inc_add_89_20_n_245, g1_inc_add_89_20_n_247,
       g1_inc_add_89_20_n_249, g1_inc_add_89_20_n_251;
  wire g1_inc_add_89_20_n_253, g1_inc_add_89_20_n_255,
       g1_inc_add_89_20_n_257, g1_inc_add_89_20_n_259,
       g1_inc_add_89_20_n_261, g1_inc_add_89_20_n_263,
       g1_inc_add_89_20_n_265, g1_inc_add_89_20_n_267;
  wire g1_inc_add_89_20_n_269, g1_inc_add_89_20_n_271,
       g1_inc_add_89_20_n_273, g1_inc_add_89_20_n_275,
       g1_inc_add_89_20_n_277, g1_inc_add_89_20_n_279,
       g1_inc_add_89_20_n_281, g1_n_531;
  wire g1_n_532, g1_n_533, g1_n_534, g1_n_535, g1_n_536, g1_n_537,
       g1_n_538, g1_n_539;
  wire g1_n_540, g1_n_541, g1_n_542, g1_n_543, g1_n_544, g1_n_545,
       g1_n_546, g1_n_547;
  wire g1_n_548, g1_n_549, g1_n_550, g1_n_551, g1_n_552, g1_n_553,
       g1_n_554, g1_n_555;
  wire g1_n_556, g1_n_557, g1_n_558, g1_n_559, g1_n_560, g1_n_561, n_0,
       n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78, n_79, n_80, n_81, n_82;
  wire n_83, n_84, n_85, n_86, n_87, n_88, n_89, n_90;
  wire n_91, n_92, n_93, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_134, n_135, n_136, n_137, n_138, n_139, n_141;
  wire n_142, n_143, n_144, n_145, n_146, n_147, n_148, n_149;
  wire n_150, n_151, n_152, n_153, n_154, n_155, n_156, n_157;
  wire n_158, n_159, n_160, n_161, n_162, n_163, n_164, n_165;
  wire n_166, n_167, n_168, n_169, n_170, n_171, n_172, n_173;
  wire n_174, n_175, n_176, n_177, n_178, n_179, n_180, n_181;
  wire n_182, n_183, n_184, n_185, n_186, n_187, n_188, n_189;
  wire n_190, n_191, n_192, n_193, n_194, n_195, n_196, n_197;
  wire n_198, n_199, n_200, n_201, n_202, n_203, n_204, n_205;
  wire n_206, n_207, n_208, n_209, n_210, n_211, n_212, n_213;
  wire n_214, n_215, n_216, n_217, n_218, n_219, n_220, n_221;
  wire n_222, n_223, n_224, n_225, n_226, n_227, n_228, n_229;
  wire n_230, n_231, n_232, n_233, n_234, n_235, n_236, n_237;
  wire n_238, n_239, n_240, n_241, n_242, n_243, n_244, n_245;
  wire n_246, n_247, n_248, n_249, n_250, n_251, n_252, n_253;
  wire n_254, n_255, n_256, n_257, n_258, n_259, n_260, n_261;
  wire n_262, n_263, n_264, n_265, n_266, n_304, n_305, n_306;
  wire n_307, n_308, n_309, n_310, n_311, n_312, n_313, n_314;
  wire n_315;
  INVX0 g1813(.INP (reset), .ZN (n_266));
  SDFFARX1 \g1_gnt_reg[0] (.RSTB (n_266), .CLK (clk), .D (n_15), .SI
       (grant1[0]), .SE (n_27), .Q (grant1[0]), .QN (UNCONNECTED));
  SDFFARX1 \g1_gnt_reg[1] (.RSTB (n_266), .CLK (clk), .D (n_22), .SI
       (grant1[1]), .SE (n_27), .Q (grant1[1]), .QN (UNCONNECTED0));
  DFFARX1 \g1_gnt_reg[2] (.RSTB (n_266), .CLK (clk), .D (n_89), .Q
       (grant1[2]), .QN (n_1));
  DFFARX1 \g1_gnt_reg[3] (.RSTB (n_266), .CLK (clk), .D (n_90), .Q
       (grant1[3]), .QN (n_9));
  DFFARX1 \g1_gnt_reg[4] (.RSTB (n_266), .CLK (clk), .D (n_138), .Q
       (grant1[4]), .QN (n_2));
  DFFARX1 \g1_gnt_reg[5] (.RSTB (n_266), .CLK (clk), .D (n_259), .Q
       (grant1[5]), .QN (n_0));
  DFFARX1 \g1_gnt_reg[6] (.RSTB (n_266), .CLK (clk), .D (n_260), .Q
       (grant1[6]), .QN (n_8));
  DFFARX1 \g1_gnt_reg[7] (.RSTB (n_266), .CLK (clk), .D (n_261), .Q
       (grant1[7]), .QN (n_6));
  SDFFARX1 \g1_s_counter_reg[0] (.RSTB (n_266), .CLK (clk), .D (n_25),
       .SI (n_44), .SE (g1_s_counter[0]), .Q (g1_s_counter[0]), .QN
       (UNCONNECTED1));
  DFFARX1 \g1_s_counter_reg[1] (.RSTB (n_266), .CLK (clk), .D (n_52),
       .Q (g1_s_counter[1]), .QN (UNCONNECTED2));
  DFFARX1 \g1_s_counter_reg[2] (.RSTB (n_266), .CLK (clk), .D (n_72),
       .Q (g1_s_counter[2]), .QN (g1_gte_48_14_n_26));
  DFFARX1 \g1_s_counter_reg[3] (.RSTB (n_266), .CLK (clk), .D (n_74),
       .Q (g1_s_counter[3]), .QN (g1_gte_48_14_n_8));
  DFFARX1 \g1_s_counter_reg[4] (.RSTB (n_266), .CLK (clk), .D (n_73),
       .Q (g1_s_counter[4]), .QN (UNCONNECTED3));
  DFFARX1 \g1_s_counter_reg[5] (.RSTB (n_266), .CLK (clk), .D (n_71),
       .Q (g1_s_counter[5]), .QN (UNCONNECTED4));
  DFFARX1 \g1_s_counter_reg[6] (.RSTB (n_266), .CLK (clk), .D (n_70),
       .Q (g1_s_counter[6]), .QN (UNCONNECTED5));
  DFFARX1 \g1_s_counter_reg[7] (.RSTB (n_266), .CLK (clk), .D (n_69),
       .Q (g1_s_counter[7]), .QN (UNCONNECTED6));
  DFFARX1 \g1_s_counter_reg[8] (.RSTB (n_266), .CLK (clk), .D (n_68),
       .Q (g1_s_counter[8]), .QN (UNCONNECTED7));
  DFFARX1 \g1_s_counter_reg[9] (.RSTB (n_266), .CLK (clk), .D (n_67),
       .Q (g1_s_counter[9]), .QN (UNCONNECTED8));
  DFFARX1 \g1_s_counter_reg[10] (.RSTB (n_266), .CLK (clk), .D (n_66),
       .Q (g1_s_counter[10]), .QN (UNCONNECTED9));
  DFFARX1 \g1_s_counter_reg[11] (.RSTB (n_266), .CLK (clk), .D (n_65),
       .Q (g1_s_counter[11]), .QN (UNCONNECTED10));
  DFFARX1 \g1_s_counter_reg[12] (.RSTB (n_266), .CLK (clk), .D (n_64),
       .Q (g1_s_counter[12]), .QN (UNCONNECTED11));
  DFFARX1 \g1_s_counter_reg[13] (.RSTB (n_266), .CLK (clk), .D (n_63),
       .Q (g1_s_counter[13]), .QN (UNCONNECTED12));
  DFFARX1 \g1_s_counter_reg[14] (.RSTB (n_266), .CLK (clk), .D (n_62),
       .Q (g1_s_counter[14]), .QN (UNCONNECTED13));
  DFFARX1 \g1_s_counter_reg[15] (.RSTB (n_266), .CLK (clk), .D (n_61),
       .Q (g1_s_counter[15]), .QN (UNCONNECTED14));
  DFFARX1 \g1_s_counter_reg[16] (.RSTB (n_266), .CLK (clk), .D (n_60),
       .Q (g1_s_counter[16]), .QN (UNCONNECTED15));
  DFFARX1 \g1_s_counter_reg[17] (.RSTB (n_266), .CLK (clk), .D (n_79),
       .Q (g1_s_counter[17]), .QN (UNCONNECTED16));
  DFFARX1 \g1_s_counter_reg[18] (.RSTB (n_266), .CLK (clk), .D (n_84),
       .Q (g1_s_counter[18]), .QN (UNCONNECTED17));
  DFFARX1 \g1_s_counter_reg[19] (.RSTB (n_266), .CLK (clk), .D (n_83),
       .Q (g1_s_counter[19]), .QN (UNCONNECTED18));
  DFFARX1 \g1_s_counter_reg[20] (.RSTB (n_266), .CLK (clk), .D (n_82),
       .Q (g1_s_counter[20]), .QN (UNCONNECTED19));
  DFFARX1 \g1_s_counter_reg[21] (.RSTB (n_266), .CLK (clk), .D (n_81),
       .Q (g1_s_counter[21]), .QN (UNCONNECTED20));
  DFFARX1 \g1_s_counter_reg[22] (.RSTB (n_266), .CLK (clk), .D (n_93),
       .Q (g1_s_counter[22]), .QN (UNCONNECTED21));
  DFFARX1 \g1_s_counter_reg[23] (.RSTB (n_266), .CLK (clk), .D (n_87),
       .Q (g1_s_counter[23]), .QN (UNCONNECTED22));
  DFFARX1 \g1_s_counter_reg[24] (.RSTB (n_266), .CLK (clk), .D (n_75),
       .Q (g1_s_counter[24]), .QN (UNCONNECTED23));
  DFFARX1 \g1_s_counter_reg[25] (.RSTB (n_266), .CLK (clk), .D (n_88),
       .Q (g1_s_counter[25]), .QN (UNCONNECTED24));
  DFFARX1 \g1_s_counter_reg[26] (.RSTB (n_266), .CLK (clk), .D (n_92),
       .Q (g1_s_counter[26]), .QN (UNCONNECTED25));
  DFFARX1 \g1_s_counter_reg[27] (.RSTB (n_266), .CLK (clk), .D (n_80),
       .Q (g1_s_counter[27]), .QN (UNCONNECTED26));
  DFFARX1 \g1_s_counter_reg[28] (.RSTB (n_266), .CLK (clk), .D (n_59),
       .Q (g1_s_counter[28]), .QN (UNCONNECTED27));
  DFFARX1 \g1_s_counter_reg[29] (.RSTB (n_266), .CLK (clk), .D (n_78),
       .Q (g1_s_counter[29]), .QN (UNCONNECTED28));
  DFFARX1 \g1_s_counter_reg[30] (.RSTB (n_266), .CLK (clk), .D (n_77),
       .Q (g1_s_counter[30]), .QN (UNCONNECTED29));
  DFFARX1 \g1_s_counter_reg[31] (.RSTB (n_266), .CLK (clk), .D (n_76),
       .Q (g1_s_counter[31]), .QN (UNCONNECTED30));
  SDFFARX1 \g1_s_weight_reg[0] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[0]), .SI (n_242), .SE (n_42), .Q (g1_s_weight[0]),
       .QN (UNCONNECTED31));
  SDFFARX1 \g1_s_weight_reg[1] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[1]), .SI (n_232), .SE (n_42), .Q (g1_s_weight[1]),
       .QN (UNCONNECTED32));
  SDFFARX1 \g1_s_weight_reg[2] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[2]), .SI (n_231), .SE (n_42), .Q (g1_s_weight[2]),
       .QN (UNCONNECTED33));
  SDFFARX1 \g1_s_weight_reg[3] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[3]), .SI (n_230), .SE (n_42), .Q (g1_s_weight[3]),
       .QN (UNCONNECTED34));
  SDFFARX1 \g1_s_weight_reg[4] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[4]), .SI (n_229), .SE (n_42), .Q (g1_s_weight[4]),
       .QN (UNCONNECTED35));
  SDFFARX1 \g1_s_weight_reg[5] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[5]), .SI (n_243), .SE (n_42), .Q (g1_s_weight[5]),
       .QN (UNCONNECTED36));
  SDFFARX1 \g1_s_weight_reg[6] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[6]), .SI (n_228), .SE (n_42), .Q (g1_s_weight[6]),
       .QN (UNCONNECTED37));
  SDFFARX1 \g1_s_weight_reg[7] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[7]), .SI (n_227), .SE (n_42), .Q (g1_s_weight[7]),
       .QN (UNCONNECTED38));
  SDFFARX1 \g1_s_weight_reg[8] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[8]), .SI (n_226), .SE (n_42), .Q (g1_s_weight[8]),
       .QN (UNCONNECTED39));
  SDFFARX1 \g1_s_weight_reg[9] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[9]), .SI (n_225), .SE (n_42), .Q (g1_s_weight[9]),
       .QN (UNCONNECTED40));
  SDFFARX1 \g1_s_weight_reg[10] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[10]), .SI (n_224), .SE (n_42), .Q
       (g1_s_weight[10]), .QN (UNCONNECTED41));
  SDFFARX1 \g1_s_weight_reg[11] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[11]), .SI (n_223), .SE (n_42), .Q
       (g1_s_weight[11]), .QN (UNCONNECTED42));
  SDFFARX1 \g1_s_weight_reg[12] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[12]), .SI (n_222), .SE (n_42), .Q
       (g1_s_weight[12]), .QN (UNCONNECTED43));
  SDFFARX1 \g1_s_weight_reg[13] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[13]), .SI (n_221), .SE (n_42), .Q
       (g1_s_weight[13]), .QN (UNCONNECTED44));
  SDFFARX1 \g1_s_weight_reg[14] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[14]), .SI (n_220), .SE (n_42), .Q
       (g1_s_weight[14]), .QN (UNCONNECTED45));
  SDFFARX1 \g1_s_weight_reg[15] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[15]), .SI (n_219), .SE (n_42), .Q
       (g1_s_weight[15]), .QN (UNCONNECTED46));
  SDFFARX1 \g1_s_weight_reg[16] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[16]), .SI (n_218), .SE (n_42), .Q
       (g1_s_weight[16]), .QN (UNCONNECTED47));
  SDFFARX1 \g1_s_weight_reg[17] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[17]), .SI (n_217), .SE (n_42), .Q
       (g1_s_weight[17]), .QN (UNCONNECTED48));
  SDFFARX1 \g1_s_weight_reg[18] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[18]), .SI (n_216), .SE (n_42), .Q
       (g1_s_weight[18]), .QN (UNCONNECTED49));
  SDFFARX1 \g1_s_weight_reg[19] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[19]), .SI (n_215), .SE (n_42), .Q
       (g1_s_weight[19]), .QN (UNCONNECTED50));
  SDFFARX1 \g1_s_weight_reg[20] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[20]), .SI (n_214), .SE (n_42), .Q
       (g1_s_weight[20]), .QN (UNCONNECTED51));
  SDFFARX1 \g1_s_weight_reg[21] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[21]), .SI (n_213), .SE (n_42), .Q
       (g1_s_weight[21]), .QN (UNCONNECTED52));
  SDFFARX1 \g1_s_weight_reg[22] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[22]), .SI (n_212), .SE (n_42), .Q
       (g1_s_weight[22]), .QN (UNCONNECTED53));
  SDFFARX1 \g1_s_weight_reg[23] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[23]), .SI (n_241), .SE (n_42), .Q
       (g1_s_weight[23]), .QN (UNCONNECTED54));
  SDFFARX1 \g1_s_weight_reg[24] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[24]), .SI (n_240), .SE (n_42), .Q
       (g1_s_weight[24]), .QN (UNCONNECTED55));
  SDFFARX1 \g1_s_weight_reg[25] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[25]), .SI (n_239), .SE (n_42), .Q
       (g1_s_weight[25]), .QN (UNCONNECTED56));
  SDFFARX1 \g1_s_weight_reg[26] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[26]), .SI (n_238), .SE (n_42), .Q
       (g1_s_weight[26]), .QN (UNCONNECTED57));
  SDFFARX1 \g1_s_weight_reg[27] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[27]), .SI (n_237), .SE (n_42), .Q
       (g1_s_weight[27]), .QN (UNCONNECTED58));
  SDFFARX1 \g1_s_weight_reg[28] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[28]), .SI (n_236), .SE (n_42), .Q
       (g1_s_weight[28]), .QN (UNCONNECTED59));
  SDFFARX1 \g1_s_weight_reg[29] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[29]), .SI (n_235), .SE (n_42), .Q
       (g1_s_weight[29]), .QN (UNCONNECTED60));
  SDFFARX1 \g1_s_weight_reg[30] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[30]), .SI (n_234), .SE (n_42), .Q
       (g1_s_weight[30]), .QN (UNCONNECTED61));
  SDFFARX1 \g1_s_weight_reg[31] (.RSTB (n_266), .CLK (clk), .D
       (g1_s_weight[31]), .SI (n_233), .SE (n_42), .Q
       (g1_s_weight[31]), .QN (UNCONNECTED62));
  DFFARX1 \g1_state_reg[1] (.RSTB (n_266), .CLK (clk), .D (n_265), .Q
       (g1_state[1]), .QN (n_3));
  DFFARX1 \g1_state_reg[2] (.RSTB (n_266), .CLK (clk), .D (n_264), .Q
       (g1_state[2]), .QN (UNCONNECTED63));
  DFFARX1 \g1_state_reg[3] (.RSTB (n_266), .CLK (clk), .D (n_201), .Q
       (g1_state[3]), .QN (UNCONNECTED64));
  DFFARX1 \ngpc_next_gnt_reg[0] (.RSTB (n_266), .CLK (clk), .D (n_251),
       .Q (s_nextGrant[0]), .QN (n_4));
  DFFARX1 \ngpc_next_gnt_reg[1] (.RSTB (n_266), .CLK (clk), .D (n_253),
       .Q (s_nextGrant[1]), .QN (UNCONNECTED65));
  DFFARX1 \ngpc_next_gnt_reg[2] (.RSTB (n_266), .CLK (clk), .D (n_250),
       .Q (s_nextGrant[2]), .QN (n_5));
  DFFARX1 \ngpc_next_gnt_reg[3] (.RSTB (n_266), .CLK (clk), .D (n_247),
       .Q (s_nextGrant[3]), .QN (UNCONNECTED66));
  DFFARX1 \ngpc_next_gnt_reg[4] (.RSTB (n_266), .CLK (clk), .D (n_248),
       .Q (s_nextGrant[4]), .QN (UNCONNECTED67));
  DFFARX1 \ngpc_next_gnt_reg[5] (.RSTB (n_266), .CLK (clk), .D (n_249),
       .Q (n_11), .QN (s_nextGrant[5]));
  DFFARX1 \ngpc_next_gnt_reg[6] (.RSTB (n_266), .CLK (clk), .D (n_246),
       .Q (s_nextGrant[6]), .QN (n_12));
  DFFARX1 \ngpc_next_gnt_reg[7] (.RSTB (n_266), .CLK (clk), .D (n_252),
       .Q (s_nextGrant[7]), .QN (UNCONNECTED68));
  DFFARX1 \ngpc_state_reg[1] (.RSTB (n_266), .CLK (clk), .D (1'b1), .Q
       (n_10), .QN (ngpc_state[1]));
  AO221X1 g8799__2398(.IN1 (n_263), .IN2 (g1_state[2]), .IN3
       (g1_state[3]), .IN4 (g1_state[1]), .IN5 (n_158), .Q (n_265));
  AO21X1 g8800__5107(.IN1 (n_262), .IN2 (n_25), .IN3 (n_42), .Q
       (n_264));
  NAND2X1 g8801__6260(.IN1 (n_262), .IN2 (n_16), .QN (n_263));
  NOR4X0 g8803__4319(.IN1 (n_258), .IN2 (g1_s_counter[26]), .IN3
       (g1_s_counter[22]), .IN4 (g1_s_counter[21]), .QN (n_262));
  AO22X1 g8805__8428(.IN1 (n_256), .IN2 (request[7]), .IN3 (n_27), .IN4
       (grant1[7]), .Q (n_261));
  NAND2X1 g8807__5526(.IN1 (n_257), .IN2 (n_39), .QN (n_260));
  AO21X1 g8808__6783(.IN1 (n_27), .IN2 (grant1[5]), .IN3 (n_255), .Q
       (n_259));
  OR4X1 g8809__3680(.IN1 (n_254), .IN2 (g1_s_counter[27]), .IN3
       (g1_s_counter[29]), .IN4 (g1_s_counter[28]), .Q (n_258));
  NAND4X0 g8810__1617(.IN1 (n_97), .IN2 (request[6]), .IN3
       (s_nextGrant[6]), .IN4 (s_nextGrant[5]), .QN (n_257));
  AND4X1 g8811__2802(.IN1 (n_97), .IN2 (s_nextGrant[7]), .IN3
       (s_nextGrant[5]), .IN4 (n_12), .Q (n_256));
  AND3X1 g8812__1705(.IN1 (n_97), .IN2 (request[5]), .IN3 (n_11), .Q
       (n_255));
  OR4X1 g8819__5122(.IN1 (n_244), .IN2 (g1_s_counter[16]), .IN3
       (g1_s_counter[14]), .IN4 (g1_s_counter[15]), .Q (n_254));
  AO22X1 g8824__8246(.IN1 (n_245), .IN2 (request[1]), .IN3 (n_36), .IN4
       (n_10), .Q (n_253));
  AO22X1 g8825__7098(.IN1 (n_245), .IN2 (request[7]), .IN3 (n_211),
       .IN4 (n_10), .Q (n_252));
  OA21X1 g8826__6131(.IN1 (n_23), .IN2 (n_245), .IN3 (request[0]), .Q
       (n_251));
  AO22X1 g8827__1881(.IN1 (n_245), .IN2 (request[2]), .IN3 (n_45), .IN4
       (n_10), .Q (n_250));
  AO22X1 g8828__5115(.IN1 (n_245), .IN2 (request[5]), .IN3 (n_135),
       .IN4 (n_10), .Q (n_249));
  AO22X1 g8829__7482(.IN1 (n_245), .IN2 (request[4]), .IN3 (n_99), .IN4
       (n_10), .Q (n_248));
  AO22X1 g8830__4733(.IN1 (n_245), .IN2 (request[3]), .IN3 (n_53), .IN4
       (n_10), .Q (n_247));
  AO22X1 g8831__6161(.IN1 (n_245), .IN2 (request[6]), .IN3 (n_139),
       .IN4 (n_10), .Q (n_246));
  NOR4X0 g8864__9315(.IN1 (n_207), .IN2 (n_211), .IN3 (n_45), .IN4
       (ngpc_state[1]), .QN (n_245));
  OR4X1 g8865__9945(.IN1 (n_208), .IN2 (g1_s_counter[18]), .IN3
       (g1_s_counter[20]), .IN4 (g1_s_counter[30]), .Q (n_244));
  AO221X1 g8866__2883(.IN1 (n_40), .IN2 (weight[133]), .IN3 (n_29),
       .IN4 (weight[165]), .IN5 (n_184), .Q (n_243));
  AO221X1 g8867__2346(.IN1 (n_40), .IN2 (weight[128]), .IN3 (n_29),
       .IN4 (weight[160]), .IN5 (n_197), .Q (n_242));
  AO221X1 g8868__1666(.IN1 (n_40), .IN2 (weight[151]), .IN3 (n_29),
       .IN4 (weight[183]), .IN5 (n_206), .Q (n_241));
  AO221X1 g8869__7410(.IN1 (n_40), .IN2 (weight[152]), .IN3 (n_29),
       .IN4 (weight[184]), .IN5 (n_205), .Q (n_240));
  AO221X1 g8870__6417(.IN1 (n_40), .IN2 (weight[153]), .IN3 (n_29),
       .IN4 (weight[185]), .IN5 (n_204), .Q (n_239));
  AO221X1 g8871__5477(.IN1 (n_40), .IN2 (weight[154]), .IN3 (n_29),
       .IN4 (weight[186]), .IN5 (n_203), .Q (n_238));
  AO221X1 g8872__2398(.IN1 (n_40), .IN2 (weight[155]), .IN3 (n_29),
       .IN4 (weight[187]), .IN5 (n_202), .Q (n_237));
  AO221X1 g8873__5107(.IN1 (n_40), .IN2 (weight[156]), .IN3 (n_29),
       .IN4 (weight[188]), .IN5 (n_210), .Q (n_236));
  AO221X1 g8874__6260(.IN1 (n_40), .IN2 (weight[157]), .IN3 (n_29),
       .IN4 (weight[189]), .IN5 (n_200), .Q (n_235));
  AO221X1 g8875__4319(.IN1 (n_40), .IN2 (weight[158]), .IN3 (n_29),
       .IN4 (weight[190]), .IN5 (n_199), .Q (n_234));
  AO221X1 g8876__8428(.IN1 (n_40), .IN2 (weight[159]), .IN3 (n_29),
       .IN4 (weight[191]), .IN5 (n_198), .Q (n_233));
  AO221X1 g8877__5526(.IN1 (n_40), .IN2 (weight[129]), .IN3 (n_29),
       .IN4 (weight[161]), .IN5 (n_196), .Q (n_232));
  AO221X1 g8878__6783(.IN1 (n_40), .IN2 (weight[130]), .IN3 (n_29),
       .IN4 (weight[162]), .IN5 (n_195), .Q (n_231));
  AO221X1 g8879__3680(.IN1 (n_40), .IN2 (weight[131]), .IN3 (n_29),
       .IN4 (weight[163]), .IN5 (n_194), .Q (n_230));
  AO221X1 g8880__1617(.IN1 (n_40), .IN2 (weight[132]), .IN3 (n_29),
       .IN4 (weight[164]), .IN5 (n_209), .Q (n_229));
  AO221X1 g8882__2802(.IN1 (n_40), .IN2 (weight[134]), .IN3 (n_29),
       .IN4 (weight[166]), .IN5 (n_192), .Q (n_228));
  AO221X1 g8883__1705(.IN1 (n_40), .IN2 (weight[135]), .IN3 (n_29),
       .IN4 (weight[167]), .IN5 (n_191), .Q (n_227));
  AO221X1 g8884__5122(.IN1 (n_40), .IN2 (weight[136]), .IN3 (n_29),
       .IN4 (weight[168]), .IN5 (n_190), .Q (n_226));
  AO221X1 g8885__8246(.IN1 (n_40), .IN2 (weight[137]), .IN3 (n_29),
       .IN4 (weight[169]), .IN5 (n_189), .Q (n_225));
  AO221X1 g8886__7098(.IN1 (n_40), .IN2 (weight[138]), .IN3 (n_29),
       .IN4 (weight[170]), .IN5 (n_188), .Q (n_224));
  AO221X1 g8887__6131(.IN1 (n_40), .IN2 (weight[139]), .IN3 (n_29),
       .IN4 (weight[171]), .IN5 (n_187), .Q (n_223));
  AO221X1 g8888__1881(.IN1 (n_40), .IN2 (weight[140]), .IN3 (n_29),
       .IN4 (weight[172]), .IN5 (n_186), .Q (n_222));
  AO221X1 g8889__5115(.IN1 (n_40), .IN2 (weight[141]), .IN3 (n_29),
       .IN4 (weight[173]), .IN5 (n_185), .Q (n_221));
  AO221X1 g8890__7482(.IN1 (n_40), .IN2 (weight[142]), .IN3 (n_29),
       .IN4 (weight[174]), .IN5 (n_193), .Q (n_220));
  AO221X1 g8891__4733(.IN1 (n_40), .IN2 (weight[143]), .IN3 (n_29),
       .IN4 (weight[175]), .IN5 (n_183), .Q (n_219));
  AO221X1 g8892__6161(.IN1 (n_40), .IN2 (weight[144]), .IN3 (n_29),
       .IN4 (weight[176]), .IN5 (n_182), .Q (n_218));
  AO221X1 g8893__9315(.IN1 (n_40), .IN2 (weight[145]), .IN3 (n_29),
       .IN4 (weight[177]), .IN5 (n_181), .Q (n_217));
  AO221X1 g8894__9945(.IN1 (n_40), .IN2 (weight[146]), .IN3 (n_29),
       .IN4 (weight[178]), .IN5 (n_180), .Q (n_216));
  AO221X1 g8895__2883(.IN1 (n_40), .IN2 (weight[147]), .IN3 (n_29),
       .IN4 (weight[179]), .IN5 (n_179), .Q (n_215));
  AO221X1 g8896__2346(.IN1 (n_40), .IN2 (weight[148]), .IN3 (n_29),
       .IN4 (weight[180]), .IN5 (n_178), .Q (n_214));
  AO221X1 g8897__1666(.IN1 (n_40), .IN2 (weight[149]), .IN3 (n_29),
       .IN4 (weight[181]), .IN5 (n_177), .Q (n_213));
  AO221X1 g8898__7410(.IN1 (n_40), .IN2 (weight[150]), .IN3 (n_29),
       .IN4 (weight[182]), .IN5 (n_176), .Q (n_212));
  AO221X1 g8899__6417(.IN1 (n_19), .IN2 (weight[220]), .IN3
       (grant1[7]), .IN4 (weight[252]), .IN5 (n_167), .Q (n_210));
  AO221X1 g8900__5477(.IN1 (n_19), .IN2 (weight[196]), .IN3
       (grant1[7]), .IN4 (weight[228]), .IN5 (n_159), .Q (n_209));
  OR4X1 g8901__2398(.IN1 (n_136), .IN2 (g1_s_counter[4]), .IN3
       (g1_s_counter[5]), .IN4 (g1_s_counter[6]), .Q (n_208));
  OR4X1 g8902__5107(.IN1 (n_139), .IN2 (n_135), .IN3 (n_132), .IN4
       (n_99), .Q (n_207));
  AO221X1 g8903__6260(.IN1 (n_19), .IN2 (weight[215]), .IN3
       (grant1[7]), .IN4 (weight[247]), .IN5 (n_172), .Q (n_206));
  AO221X1 g8904__4319(.IN1 (n_19), .IN2 (weight[216]), .IN3
       (grant1[7]), .IN4 (weight[248]), .IN5 (n_171), .Q (n_205));
  AO221X1 g8905__8428(.IN1 (n_19), .IN2 (weight[217]), .IN3
       (grant1[7]), .IN4 (weight[249]), .IN5 (n_170), .Q (n_204));
  AO221X1 g8906__5526(.IN1 (n_19), .IN2 (weight[218]), .IN3
       (grant1[7]), .IN4 (weight[250]), .IN5 (n_169), .Q (n_203));
  AO221X1 g8907__6783(.IN1 (n_19), .IN2 (weight[219]), .IN3
       (grant1[7]), .IN4 (weight[251]), .IN5 (n_168), .Q (n_202));
  NOR2X0 g8908__3680(.IN1 (n_174), .IN2 (n_27), .QN (n_201));
  AO221X1 g8909__1617(.IN1 (n_19), .IN2 (weight[221]), .IN3
       (grant1[7]), .IN4 (weight[253]), .IN5 (n_166), .Q (n_200));
  AO221X1 g8910__2802(.IN1 (n_19), .IN2 (weight[222]), .IN3
       (grant1[7]), .IN4 (weight[254]), .IN5 (n_165), .Q (n_199));
  AO221X1 g8911__1705(.IN1 (n_19), .IN2 (weight[223]), .IN3
       (grant1[7]), .IN4 (weight[255]), .IN5 (n_164), .Q (n_198));
  AO221X1 g8912__5122(.IN1 (n_19), .IN2 (weight[192]), .IN3
       (grant1[7]), .IN4 (weight[224]), .IN5 (n_163), .Q (n_197));
  AO221X1 g8913__8246(.IN1 (n_19), .IN2 (weight[193]), .IN3
       (grant1[7]), .IN4 (weight[225]), .IN5 (n_162), .Q (n_196));
  AO221X1 g8914__7098(.IN1 (n_19), .IN2 (weight[194]), .IN3
       (grant1[7]), .IN4 (weight[226]), .IN5 (n_161), .Q (n_195));
  AO221X1 g8915__6131(.IN1 (n_19), .IN2 (weight[195]), .IN3
       (grant1[7]), .IN4 (weight[227]), .IN5 (n_160), .Q (n_194));
  AND2X1 g8916__1881(.IN1 (n_175), .IN2 (request[7]), .Q (n_211));
  AO221X1 g8917__5115(.IN1 (n_19), .IN2 (weight[206]), .IN3
       (grant1[7]), .IN4 (weight[238]), .IN5 (n_149), .Q (n_193));
  AO221X1 g8918__7482(.IN1 (n_19), .IN2 (weight[198]), .IN3
       (grant1[7]), .IN4 (weight[230]), .IN5 (n_157), .Q (n_192));
  AO221X1 g8919__4733(.IN1 (n_19), .IN2 (weight[199]), .IN3
       (grant1[7]), .IN4 (weight[231]), .IN5 (n_156), .Q (n_191));
  AO221X1 g8920__6161(.IN1 (n_19), .IN2 (weight[200]), .IN3
       (grant1[7]), .IN4 (weight[232]), .IN5 (n_155), .Q (n_190));
  AO221X1 g8921__9315(.IN1 (n_19), .IN2 (weight[201]), .IN3
       (grant1[7]), .IN4 (weight[233]), .IN5 (n_154), .Q (n_189));
  AO221X1 g8922__9945(.IN1 (n_19), .IN2 (weight[202]), .IN3
       (grant1[7]), .IN4 (weight[234]), .IN5 (n_153), .Q (n_188));
  AO221X1 g8923__2883(.IN1 (n_19), .IN2 (weight[203]), .IN3
       (grant1[7]), .IN4 (weight[235]), .IN5 (n_152), .Q (n_187));
  AO221X1 g8924__2346(.IN1 (n_19), .IN2 (weight[204]), .IN3
       (grant1[7]), .IN4 (weight[236]), .IN5 (n_151), .Q (n_186));
  AO221X1 g8925__1666(.IN1 (n_19), .IN2 (weight[205]), .IN3
       (grant1[7]), .IN4 (weight[237]), .IN5 (n_150), .Q (n_185));
  AO221X1 g8926__7410(.IN1 (n_19), .IN2 (weight[197]), .IN3
       (grant1[7]), .IN4 (weight[229]), .IN5 (n_173), .Q (n_184));
  AO221X1 g8927__6417(.IN1 (n_19), .IN2 (weight[207]), .IN3
       (grant1[7]), .IN4 (weight[239]), .IN5 (n_148), .Q (n_183));
  AO221X1 g8928__5477(.IN1 (n_19), .IN2 (weight[208]), .IN3
       (grant1[7]), .IN4 (weight[240]), .IN5 (n_147), .Q (n_182));
  AO221X1 g8929__2398(.IN1 (n_19), .IN2 (weight[209]), .IN3
       (grant1[7]), .IN4 (weight[241]), .IN5 (n_146), .Q (n_181));
  AO221X1 g8930__5107(.IN1 (n_19), .IN2 (weight[210]), .IN3
       (grant1[7]), .IN4 (weight[242]), .IN5 (n_145), .Q (n_180));
  AO221X1 g8931__6260(.IN1 (n_19), .IN2 (weight[211]), .IN3
       (grant1[7]), .IN4 (weight[243]), .IN5 (n_144), .Q (n_179));
  AO221X1 g8932__4319(.IN1 (n_19), .IN2 (weight[212]), .IN3
       (grant1[7]), .IN4 (weight[244]), .IN5 (n_143), .Q (n_178));
  AO221X1 g8933__8428(.IN1 (n_19), .IN2 (weight[213]), .IN3
       (grant1[7]), .IN4 (weight[245]), .IN5 (n_142), .Q (n_177));
  AO221X1 g8934__5526(.IN1 (n_19), .IN2 (weight[214]), .IN3
       (grant1[7]), .IN4 (weight[246]), .IN5 (n_141), .Q (n_176));
  HADDX1 g8935__6783(.A0 (n_8), .B0 (n_98), .SO (n_175), .C1 (n_174));
  AO221X1 g8936__3680(.IN1 (n_95), .IN2 (weight[5]), .IN3 (n_96), .IN4
       (weight[37]), .IN5 (n_134), .Q (n_173));
  AO221X1 g8937__1617(.IN1 (n_95), .IN2 (weight[23]), .IN3 (n_96), .IN4
       (weight[55]), .IN5 (n_130), .Q (n_172));
  AO221X1 g8938__2802(.IN1 (n_95), .IN2 (weight[24]), .IN3 (n_96), .IN4
       (weight[56]), .IN5 (n_129), .Q (n_171));
  AO221X1 g8939__1705(.IN1 (n_95), .IN2 (weight[25]), .IN3 (n_96), .IN4
       (weight[57]), .IN5 (n_128), .Q (n_170));
  AO221X1 g8940__5122(.IN1 (n_95), .IN2 (weight[26]), .IN3 (n_96), .IN4
       (weight[58]), .IN5 (n_127), .Q (n_169));
  AO221X1 g8941__8246(.IN1 (n_95), .IN2 (weight[27]), .IN3 (n_96), .IN4
       (weight[59]), .IN5 (n_126), .Q (n_168));
  AO221X1 g8942__7098(.IN1 (n_95), .IN2 (weight[28]), .IN3 (n_96), .IN4
       (weight[60]), .IN5 (n_125), .Q (n_167));
  AO221X1 g8943__6131(.IN1 (n_95), .IN2 (weight[29]), .IN3 (n_96), .IN4
       (weight[61]), .IN5 (n_124), .Q (n_166));
  AO221X1 g8944__1881(.IN1 (n_95), .IN2 (weight[30]), .IN3 (n_96), .IN4
       (weight[62]), .IN5 (n_122), .Q (n_165));
  AO221X1 g8945__5115(.IN1 (n_95), .IN2 (weight[31]), .IN3 (n_96), .IN4
       (weight[63]), .IN5 (n_121), .Q (n_164));
  AO221X1 g8946__7482(.IN1 (n_95), .IN2 (weight[0]), .IN3 (n_96), .IN4
       (weight[32]), .IN5 (n_123), .Q (n_163));
  AO221X1 g8947__4733(.IN1 (n_95), .IN2 (weight[1]), .IN3 (n_96), .IN4
       (weight[33]), .IN5 (n_120), .Q (n_162));
  AO221X1 g8948__6161(.IN1 (n_95), .IN2 (weight[2]), .IN3 (n_96), .IN4
       (weight[34]), .IN5 (n_119), .Q (n_161));
  AO221X1 g8949__9315(.IN1 (n_95), .IN2 (weight[3]), .IN3 (n_96), .IN4
       (weight[35]), .IN5 (n_118), .Q (n_160));
  AO221X1 g8950__9945(.IN1 (n_95), .IN2 (weight[4]), .IN3 (n_96), .IN4
       (weight[36]), .IN5 (n_117), .Q (n_159));
  NOR2X0 g8951__2883(.IN1 (n_315), .IN2 (g1_state[2]), .QN (n_158));
  AO221X1 g8953__2346(.IN1 (n_95), .IN2 (weight[6]), .IN3 (n_96), .IN4
       (weight[38]), .IN5 (n_115), .Q (n_157));
  AO221X1 g8954__1666(.IN1 (n_95), .IN2 (weight[7]), .IN3 (n_96), .IN4
       (weight[39]), .IN5 (n_114), .Q (n_156));
  AO221X1 g8955__7410(.IN1 (n_95), .IN2 (weight[8]), .IN3 (n_96), .IN4
       (weight[40]), .IN5 (n_113), .Q (n_155));
  AO221X1 g8956__6417(.IN1 (n_95), .IN2 (weight[9]), .IN3 (n_96), .IN4
       (weight[41]), .IN5 (n_112), .Q (n_154));
  AO221X1 g8957__5477(.IN1 (n_95), .IN2 (weight[10]), .IN3 (n_96), .IN4
       (weight[42]), .IN5 (n_111), .Q (n_153));
  AO221X1 g8958__2398(.IN1 (n_95), .IN2 (weight[11]), .IN3 (n_96), .IN4
       (weight[43]), .IN5 (n_110), .Q (n_152));
  AO221X1 g8959__5107(.IN1 (n_95), .IN2 (weight[12]), .IN3 (n_96), .IN4
       (weight[44]), .IN5 (n_109), .Q (n_151));
  AO221X1 g8960__6260(.IN1 (n_95), .IN2 (weight[13]), .IN3 (n_96), .IN4
       (weight[45]), .IN5 (n_108), .Q (n_150));
  AO221X1 g8961__4319(.IN1 (n_95), .IN2 (weight[14]), .IN3 (n_96), .IN4
       (weight[46]), .IN5 (n_107), .Q (n_149));
  AO221X1 g8962__8428(.IN1 (n_95), .IN2 (weight[15]), .IN3 (n_96), .IN4
       (weight[47]), .IN5 (n_106), .Q (n_148));
  AO221X1 g8963__5526(.IN1 (n_95), .IN2 (weight[16]), .IN3 (n_96), .IN4
       (weight[48]), .IN5 (n_105), .Q (n_147));
  AO221X1 g8964__6783(.IN1 (n_95), .IN2 (weight[17]), .IN3 (n_96), .IN4
       (weight[49]), .IN5 (n_104), .Q (n_146));
  AO221X1 g8965__3680(.IN1 (n_95), .IN2 (weight[18]), .IN3 (n_96), .IN4
       (weight[50]), .IN5 (n_103), .Q (n_145));
  AO221X1 g8966__1617(.IN1 (n_95), .IN2 (weight[19]), .IN3 (n_96), .IN4
       (weight[51]), .IN5 (n_102), .Q (n_144));
  AO221X1 g8967__2802(.IN1 (n_95), .IN2 (weight[20]), .IN3 (n_96), .IN4
       (weight[52]), .IN5 (n_101), .Q (n_143));
  AO221X1 g8968__1705(.IN1 (n_95), .IN2 (weight[21]), .IN3 (n_96), .IN4
       (weight[53]), .IN5 (n_100), .Q (n_142));
  AO221X1 g8969__5122(.IN1 (n_95), .IN2 (weight[22]), .IN3 (n_96), .IN4
       (weight[54]), .IN5 (n_116), .Q (n_141));
  AO21X1 g8971__7098(.IN1 (n_27), .IN2 (grant1[4]), .IN3 (n_131), .Q
       (n_138));
  NOR2X0 g8972__6131(.IN1 (n_137), .IN2 (n_98), .QN (n_139));
  NAND2X1 g8973__1881(.IN1 (n_91), .IN2 (request[6]), .QN (n_137));
  NAND2X1 g8974__5115(.IN1 (n_85), .IN2 (n_86), .QN (n_136));
  AO22X1 g9008__7482(.IN1 (n_57), .IN2 (weight[69]), .IN3 (n_43), .IN4
       (weight[101]), .Q (n_134));
  OR3X1 g9010__6161(.IN1 (n_53), .IN2 (n_36), .IN3 (n_18), .Q (n_132));
  AND3X1 g9011__9315(.IN1 (n_55), .IN2 (s_nextGrant[4]), .IN3
       (request[4]), .Q (n_131));
  AO22X1 g9012__9945(.IN1 (n_57), .IN2 (weight[87]), .IN3 (n_43), .IN4
       (weight[119]), .Q (n_130));
  AO22X1 g9013__2883(.IN1 (n_57), .IN2 (weight[88]), .IN3 (n_43), .IN4
       (weight[120]), .Q (n_129));
  AO22X1 g9014__2346(.IN1 (n_57), .IN2 (weight[89]), .IN3 (n_43), .IN4
       (weight[121]), .Q (n_128));
  AO22X1 g9015__1666(.IN1 (n_57), .IN2 (weight[90]), .IN3 (n_43), .IN4
       (weight[122]), .Q (n_127));
  AO22X1 g9016__7410(.IN1 (n_57), .IN2 (weight[91]), .IN3 (n_43), .IN4
       (weight[123]), .Q (n_126));
  AO22X1 g9017__6417(.IN1 (n_57), .IN2 (weight[92]), .IN3 (n_43), .IN4
       (weight[124]), .Q (n_125));
  AO22X1 g9018__5477(.IN1 (n_57), .IN2 (weight[93]), .IN3 (n_43), .IN4
       (weight[125]), .Q (n_124));
  AO22X1 g9019__2398(.IN1 (n_57), .IN2 (weight[64]), .IN3 (n_43), .IN4
       (weight[96]), .Q (n_123));
  AO22X1 g9020__5107(.IN1 (n_57), .IN2 (weight[94]), .IN3 (n_43), .IN4
       (weight[126]), .Q (n_122));
  AO22X1 g9021__6260(.IN1 (n_57), .IN2 (weight[95]), .IN3 (n_43), .IN4
       (weight[127]), .Q (n_121));
  AO22X1 g9022__4319(.IN1 (n_57), .IN2 (weight[65]), .IN3 (n_43), .IN4
       (weight[97]), .Q (n_120));
  AO22X1 g9023__8428(.IN1 (n_57), .IN2 (weight[66]), .IN3 (n_43), .IN4
       (weight[98]), .Q (n_119));
  AO22X1 g9024__5526(.IN1 (n_57), .IN2 (weight[67]), .IN3 (n_43), .IN4
       (weight[99]), .Q (n_118));
  AO22X1 g9025__6783(.IN1 (n_57), .IN2 (weight[68]), .IN3 (n_43), .IN4
       (weight[100]), .Q (n_117));
  AO22X1 g9026__3680(.IN1 (n_57), .IN2 (weight[86]), .IN3 (n_43), .IN4
       (weight[118]), .Q (n_116));
  AO22X1 g9027__1617(.IN1 (n_57), .IN2 (weight[70]), .IN3 (n_43), .IN4
       (weight[102]), .Q (n_115));
  AO22X1 g9028__2802(.IN1 (n_57), .IN2 (weight[71]), .IN3 (n_43), .IN4
       (weight[103]), .Q (n_114));
  AO22X1 g9029__1705(.IN1 (n_57), .IN2 (weight[72]), .IN3 (n_43), .IN4
       (weight[104]), .Q (n_113));
  AO22X1 g9030__5122(.IN1 (n_57), .IN2 (weight[73]), .IN3 (n_43), .IN4
       (weight[105]), .Q (n_112));
  AO22X1 g9031__8246(.IN1 (n_57), .IN2 (weight[74]), .IN3 (n_43), .IN4
       (weight[106]), .Q (n_111));
  AO22X1 g9032__7098(.IN1 (n_57), .IN2 (weight[75]), .IN3 (n_43), .IN4
       (weight[107]), .Q (n_110));
  AO22X1 g9033__6131(.IN1 (n_57), .IN2 (weight[76]), .IN3 (n_43), .IN4
       (weight[108]), .Q (n_109));
  AO22X1 g9034__1881(.IN1 (n_57), .IN2 (weight[77]), .IN3 (n_43), .IN4
       (weight[109]), .Q (n_108));
  AO22X1 g9035__5115(.IN1 (n_57), .IN2 (weight[78]), .IN3 (n_43), .IN4
       (weight[110]), .Q (n_107));
  AO22X1 g9036__7482(.IN1 (n_57), .IN2 (weight[79]), .IN3 (n_43), .IN4
       (weight[111]), .Q (n_106));
  AO22X1 g9037__4733(.IN1 (n_57), .IN2 (weight[80]), .IN3 (n_43), .IN4
       (weight[112]), .Q (n_105));
  AO22X1 g9038__6161(.IN1 (n_57), .IN2 (weight[81]), .IN3 (n_43), .IN4
       (weight[113]), .Q (n_104));
  AO22X1 g9039__9315(.IN1 (n_57), .IN2 (weight[82]), .IN3 (n_43), .IN4
       (weight[114]), .Q (n_103));
  AO22X1 g9040__9945(.IN1 (n_57), .IN2 (weight[83]), .IN3 (n_43), .IN4
       (weight[115]), .Q (n_102));
  AO22X1 g9041__2883(.IN1 (n_57), .IN2 (weight[84]), .IN3 (n_43), .IN4
       (weight[116]), .Q (n_101));
  AO22X1 g9042__2346(.IN1 (n_57), .IN2 (weight[85]), .IN3 (n_43), .IN4
       (weight[117]), .Q (n_100));
  AND3X1 g9043__1666(.IN1 (n_58), .IN2 (n_56), .IN3 (request[5]), .Q
       (n_135));
  AO22X1 g9045__7410(.IN1 (n_44), .IN2 (g1_s_counter[22]), .IN3
       (g1_n_540), .IN4 (n_25), .Q (n_93));
  AO22X1 g9046__6417(.IN1 (n_44), .IN2 (g1_s_counter[26]), .IN3
       (g1_n_536), .IN4 (n_25), .Q (n_92));
  NAND2X1 g9047__5477(.IN1 (n_58), .IN2 (grant1[5]), .QN (n_91));
  NAND2X1 g9048__2398(.IN1 (n_50), .IN2 (n_38), .QN (n_90));
  AO21X1 g9049__5107(.IN1 (n_27), .IN2 (grant1[2]), .IN3 (n_51), .Q
       (n_89));
  AO22X1 g9050__6260(.IN1 (n_44), .IN2 (g1_s_counter[25]), .IN3
       (g1_n_537), .IN4 (n_25), .Q (n_88));
  AO22X1 g9051__4319(.IN1 (n_44), .IN2 (g1_s_counter[23]), .IN3
       (g1_n_539), .IN4 (n_25), .Q (n_87));
  NOR4X0 g9052__8428(.IN1 (n_31), .IN2 (g1_s_counter[17]), .IN3
       (g1_s_counter[23]), .IN4 (g1_s_counter[11]), .QN (n_86));
  NOR4X0 g9053__5526(.IN1 (n_32), .IN2 (g1_s_counter[7]), .IN3
       (g1_s_counter[8]), .IN4 (g1_s_counter[9]), .QN (n_85));
  AO22X1 g9054__6783(.IN1 (n_44), .IN2 (g1_s_counter[18]), .IN3
       (g1_n_544), .IN4 (n_25), .Q (n_84));
  AO22X1 g9055__3680(.IN1 (n_44), .IN2 (g1_s_counter[19]), .IN3
       (g1_n_543), .IN4 (n_25), .Q (n_83));
  AO22X1 g9056__1617(.IN1 (n_44), .IN2 (g1_s_counter[20]), .IN3
       (g1_n_542), .IN4 (n_25), .Q (n_82));
  AO22X1 g9057__2802(.IN1 (n_44), .IN2 (g1_s_counter[21]), .IN3
       (g1_n_541), .IN4 (n_25), .Q (n_81));
  AO22X1 g9058__1705(.IN1 (n_44), .IN2 (g1_s_counter[27]), .IN3
       (g1_n_535), .IN4 (n_25), .Q (n_80));
  AND3X1 g9060__5122(.IN1 (n_49), .IN2 (n_46), .IN3 (request[4]), .Q
       (n_99));
  NOR2X0 g9061__8246(.IN1 (n_58), .IN2 (grant1[5]), .QN (n_98));
  NOR2X0 g9062__7098(.IN1 (n_54), .IN2 (s_nextGrant[4]), .QN (n_97));
  AND3X1 g9063__6131(.IN1 (n_47), .IN2 (grant1[1]), .IN3 (n_1), .Q
       (n_96));
  NOR3X0 g9064__1881(.IN1 (n_48), .IN2 (grant1[2]), .IN3 (grant1[1]),
       .QN (n_95));
  AO22X1 g9065__5115(.IN1 (n_44), .IN2 (g1_s_counter[17]), .IN3
       (g1_n_545), .IN4 (n_25), .Q (n_79));
  AO22X1 g9066__7482(.IN1 (n_44), .IN2 (g1_s_counter[29]), .IN3
       (g1_n_533), .IN4 (n_25), .Q (n_78));
  AO22X1 g9067__4733(.IN1 (n_44), .IN2 (g1_s_counter[30]), .IN3
       (g1_n_532), .IN4 (n_25), .Q (n_77));
  AO22X1 g9068__6161(.IN1 (n_44), .IN2 (g1_s_counter[31]), .IN3
       (g1_n_531), .IN4 (n_25), .Q (n_76));
  AO22X1 g9069__9315(.IN1 (n_44), .IN2 (g1_s_counter[24]), .IN3
       (g1_n_538), .IN4 (n_25), .Q (n_75));
  AO22X1 g9070__9945(.IN1 (n_44), .IN2 (g1_s_counter[3]), .IN3
       (g1_n_559), .IN4 (n_25), .Q (n_74));
  AO22X1 g9071__2883(.IN1 (n_44), .IN2 (g1_s_counter[4]), .IN3
       (g1_n_558), .IN4 (n_25), .Q (n_73));
  AO22X1 g9072__2346(.IN1 (n_44), .IN2 (g1_s_counter[2]), .IN3
       (g1_n_560), .IN4 (n_25), .Q (n_72));
  AO22X1 g9073__1666(.IN1 (n_44), .IN2 (g1_s_counter[5]), .IN3
       (g1_n_557), .IN4 (n_25), .Q (n_71));
  AO22X1 g9074__7410(.IN1 (n_44), .IN2 (g1_s_counter[6]), .IN3
       (g1_n_556), .IN4 (n_25), .Q (n_70));
  AO22X1 g9075__6417(.IN1 (n_44), .IN2 (g1_s_counter[7]), .IN3
       (g1_n_555), .IN4 (n_25), .Q (n_69));
  AO22X1 g9076__5477(.IN1 (n_44), .IN2 (g1_s_counter[8]), .IN3
       (g1_n_554), .IN4 (n_25), .Q (n_68));
  AO22X1 g9077__2398(.IN1 (n_44), .IN2 (g1_s_counter[9]), .IN3
       (g1_n_553), .IN4 (n_25), .Q (n_67));
  AO22X1 g9078__5107(.IN1 (n_44), .IN2 (g1_s_counter[10]), .IN3
       (g1_n_552), .IN4 (n_25), .Q (n_66));
  AO22X1 g9079__6260(.IN1 (n_44), .IN2 (g1_s_counter[11]), .IN3
       (g1_n_551), .IN4 (n_25), .Q (n_65));
  AO22X1 g9080__4319(.IN1 (n_44), .IN2 (g1_s_counter[12]), .IN3
       (g1_n_550), .IN4 (n_25), .Q (n_64));
  AO22X1 g9081__8428(.IN1 (n_44), .IN2 (g1_s_counter[13]), .IN3
       (g1_n_549), .IN4 (n_25), .Q (n_63));
  AO22X1 g9082__5526(.IN1 (n_44), .IN2 (g1_s_counter[14]), .IN3
       (g1_n_548), .IN4 (n_25), .Q (n_62));
  AO22X1 g9083__6783(.IN1 (n_44), .IN2 (g1_s_counter[15]), .IN3
       (g1_n_547), .IN4 (n_25), .Q (n_61));
  AO22X1 g9084__3680(.IN1 (n_44), .IN2 (g1_s_counter[16]), .IN3
       (g1_n_546), .IN4 (n_25), .Q (n_60));
  AO22X1 g9085__1617(.IN1 (n_44), .IN2 (g1_s_counter[28]), .IN3
       (g1_n_534), .IN4 (n_25), .Q (n_59));
  NAND2X1 g9086__2802(.IN1 (n_49), .IN2 (grant1[4]), .QN (n_56));
  OR2X1 g9087__1705(.IN1 (n_49), .IN2 (grant1[4]), .Q (n_58));
  NOR2X0 g9090__5122(.IN1 (n_48), .IN2 (n_1), .QN (n_57));
  INVX0 g9091(.INP (n_54), .ZN (n_55));
  AO221X1 g9092__8246(.IN1 (n_25), .IN2 (g1_n_561), .IN3 (n_24), .IN4
       (g1_s_counter[1]), .IN5 (n_26), .Q (n_52));
  AND3X1 g9093__7098(.IN1 (n_34), .IN2 (s_nextGrant[2]), .IN3
       (request[2]), .Q (n_51));
  NAND4X0 g9094__6131(.IN1 (n_34), .IN2 (s_nextGrant[3]), .IN3 (n_5),
       .IN4 (request[3]), .QN (n_50));
  OR3X1 g9095__1881(.IN1 (n_33), .IN2 (s_nextGrant[2]), .IN3
       (s_nextGrant[3]), .Q (n_54));
  AND3X1 g9096__5115(.IN1 (n_37), .IN2 (n_41), .IN3 (request[3]), .Q
       (n_53));
  INVX0 g9097(.INP (n_47), .ZN (n_48));
  NAND2X1 g9098__7482(.IN1 (n_41), .IN2 (grant1[3]), .QN (n_46));
  OR2X1 g9099__4733(.IN1 (n_41), .IN2 (grant1[3]), .Q (n_49));
  NOR2X0 g9100__6161(.IN1 (n_35), .IN2 (grant1[3]), .QN (n_47));
  AND3X1 g9101__9315(.IN1 (n_30), .IN2 (n_28), .IN3 (request[2]), .Q
       (n_45));
  OR3X1 g9102__9945(.IN1 (n_17), .IN2 (n_14), .IN3 (g1_state[3]), .Q
       (n_44));
  NOR2X0 g9103__2883(.IN1 (n_35), .IN2 (n_9), .QN (n_43));
  AND2X1 g9104__2346(.IN1 (n_17), .IN2 (g1_state[3]), .Q (n_42));
  NAND2X1 g9105__1666(.IN1 (n_27), .IN2 (grant1[6]), .QN (n_39));
  NAND2X1 g9106__7410(.IN1 (n_27), .IN2 (grant1[3]), .QN (n_38));
  NAND2X1 g9107__6417(.IN1 (n_30), .IN2 (grant1[2]), .QN (n_37));
  OR2X1 g9108__5477(.IN1 (n_30), .IN2 (grant1[2]), .Q (n_41));
  AND3X1 g9109__2398(.IN1 (n_21), .IN2 (grant1[4]), .IN3 (n_0), .Q
       (n_40));
  INVX0 g9110(.INP (n_34), .ZN (n_33));
  OR4X1 g9111__5107(.IN1 (n_305), .IN2 (g1_s_counter[25]), .IN3
       (g1_s_counter[13]), .IN4 (g1_s_counter[31]), .Q (n_32));
  OR4X1 g9112__6260(.IN1 (g1_s_counter[10]), .IN2 (g1_s_counter[12]),
       .IN3 (g1_s_counter[19]), .IN4 (g1_s_counter[24]), .Q (n_31));
  AND3X1 g9113__4319(.IN1 (n_13), .IN2 (n_20), .IN3 (request[1]), .Q
       (n_36));
  NAND3X0 g9114__8428(.IN1 (n_21), .IN2 (n_0), .IN3 (n_2), .QN (n_35));
  NOR3X0 g9115__5526(.IN1 (n_27), .IN2 (s_nextGrant[0]), .IN3
       (s_nextGrant[1]), .QN (n_34));
  NAND2X1 g9116__6783(.IN1 (n_20), .IN2 (grant1[1]), .QN (n_28));
  OR2X1 g9117__3680(.IN1 (n_20), .IN2 (grant1[1]), .Q (n_30));
  AND2X1 g9118__1617(.IN1 (n_21), .IN2 (grant1[5]), .Q (n_29));
  INVX0 g9119(.INP (n_26), .ZN (n_27));
  INVX0 g9120(.INP (n_24), .ZN (n_25));
  NOR2X0 g9121__2802(.IN1 (n_6), .IN2 (ngpc_state[1]), .QN (n_23));
  AND3X1 g9122__1705(.IN1 (s_nextGrant[1]), .IN2 (n_4), .IN3
       (request[1]), .Q (n_22));
  NOR3X0 g9123__5122(.IN1 (g1_state[3]), .IN2 (g1_state[2]), .IN3
       (n_3), .QN (n_26));
  NAND2X1 g9124__8246(.IN1 (n_16), .IN2 (g1_state[2]), .QN (n_24));
  AND2X1 g9126__7098(.IN1 (grant1[7]), .IN2 (request[0]), .Q (n_18));
  NOR2X0 g9127__6131(.IN1 (grant1[6]), .IN2 (grant1[7]), .QN (n_21));
  OR2X1 g9128__1881(.IN1 (grant1[7]), .IN2 (grant1[0]), .Q (n_20));
  NOR2X0 g9130__5115(.IN1 (grant1[7]), .IN2 (n_8), .QN (n_19));
  AND2X1 g9131__7482(.IN1 (s_nextGrant[0]), .IN2 (request[0]), .Q
       (n_15));
  AND2X1 g9132__4733(.IN1 (g1_state[2]), .IN2 (g1_state[1]), .Q (n_14));
  NAND2X1 g9133__6161(.IN1 (grant1[7]), .IN2 (grant1[0]), .QN (n_13));
  NOR2X0 g9134__9315(.IN1 (g1_state[1]), .IN2 (g1_state[2]), .QN
       (n_17));
  NOR2X0 g9135__9945(.IN1 (g1_state[3]), .IN2 (g1_state[1]), .QN
       (n_16));
  XNOR2X1 g1_inc_add_89_20_g407__2883(.IN1 (g1_inc_add_89_20_n_221),
       .IN2 (g1_s_counter[31]), .Q (g1_n_531));
  OA21X1 g1_inc_add_89_20_g408__2346(.IN1 (g1_s_counter[30]), .IN2
       (g1_inc_add_89_20_n_224), .IN3 (g1_inc_add_89_20_n_221), .Q
       (g1_n_532));
  NAND2X1 g1_inc_add_89_20_g409__1666(.IN1 (g1_inc_add_89_20_n_224),
       .IN2 (g1_s_counter[30]), .QN (g1_inc_add_89_20_n_221));
  HADDX1 g1_inc_add_89_20_g410__7410(.A0 (g1_s_counter[29]), .B0
       (g1_inc_add_89_20_n_227), .SO (g1_n_533), .C1
       (g1_inc_add_89_20_n_224));
  HADDX1 g1_inc_add_89_20_g411__6417(.A0 (g1_s_counter[28]), .B0
       (g1_inc_add_89_20_n_229), .SO (g1_n_534), .C1
       (g1_inc_add_89_20_n_227));
  HADDX1 g1_inc_add_89_20_g412__5477(.A0 (g1_s_counter[27]), .B0
       (g1_inc_add_89_20_n_231), .SO (g1_n_535), .C1
       (g1_inc_add_89_20_n_229));
  HADDX1 g1_inc_add_89_20_g413__2398(.A0 (g1_s_counter[26]), .B0
       (g1_inc_add_89_20_n_233), .SO (g1_n_536), .C1
       (g1_inc_add_89_20_n_231));
  HADDX1 g1_inc_add_89_20_g414__5107(.A0 (g1_s_counter[25]), .B0
       (g1_inc_add_89_20_n_235), .SO (g1_n_537), .C1
       (g1_inc_add_89_20_n_233));
  HADDX1 g1_inc_add_89_20_g415__6260(.A0 (g1_s_counter[24]), .B0
       (g1_inc_add_89_20_n_237), .SO (g1_n_538), .C1
       (g1_inc_add_89_20_n_235));
  HADDX1 g1_inc_add_89_20_g416__4319(.A0 (g1_s_counter[23]), .B0
       (g1_inc_add_89_20_n_239), .SO (g1_n_539), .C1
       (g1_inc_add_89_20_n_237));
  HADDX1 g1_inc_add_89_20_g417__8428(.A0 (g1_s_counter[22]), .B0
       (g1_inc_add_89_20_n_241), .SO (g1_n_540), .C1
       (g1_inc_add_89_20_n_239));
  HADDX1 g1_inc_add_89_20_g418__5526(.A0 (g1_s_counter[21]), .B0
       (g1_inc_add_89_20_n_243), .SO (g1_n_541), .C1
       (g1_inc_add_89_20_n_241));
  HADDX1 g1_inc_add_89_20_g419__6783(.A0 (g1_s_counter[20]), .B0
       (g1_inc_add_89_20_n_245), .SO (g1_n_542), .C1
       (g1_inc_add_89_20_n_243));
  HADDX1 g1_inc_add_89_20_g420__3680(.A0 (g1_s_counter[19]), .B0
       (g1_inc_add_89_20_n_247), .SO (g1_n_543), .C1
       (g1_inc_add_89_20_n_245));
  HADDX1 g1_inc_add_89_20_g421__1617(.A0 (g1_s_counter[18]), .B0
       (g1_inc_add_89_20_n_249), .SO (g1_n_544), .C1
       (g1_inc_add_89_20_n_247));
  HADDX1 g1_inc_add_89_20_g422__2802(.A0 (g1_s_counter[17]), .B0
       (g1_inc_add_89_20_n_251), .SO (g1_n_545), .C1
       (g1_inc_add_89_20_n_249));
  HADDX1 g1_inc_add_89_20_g423__1705(.A0 (g1_s_counter[16]), .B0
       (g1_inc_add_89_20_n_253), .SO (g1_n_546), .C1
       (g1_inc_add_89_20_n_251));
  HADDX1 g1_inc_add_89_20_g424__5122(.A0 (g1_s_counter[15]), .B0
       (g1_inc_add_89_20_n_255), .SO (g1_n_547), .C1
       (g1_inc_add_89_20_n_253));
  HADDX1 g1_inc_add_89_20_g425__8246(.A0 (g1_s_counter[14]), .B0
       (g1_inc_add_89_20_n_257), .SO (g1_n_548), .C1
       (g1_inc_add_89_20_n_255));
  HADDX1 g1_inc_add_89_20_g426__7098(.A0 (g1_s_counter[13]), .B0
       (g1_inc_add_89_20_n_259), .SO (g1_n_549), .C1
       (g1_inc_add_89_20_n_257));
  HADDX1 g1_inc_add_89_20_g427__6131(.A0 (g1_s_counter[12]), .B0
       (g1_inc_add_89_20_n_261), .SO (g1_n_550), .C1
       (g1_inc_add_89_20_n_259));
  HADDX1 g1_inc_add_89_20_g428__1881(.A0 (g1_s_counter[11]), .B0
       (g1_inc_add_89_20_n_263), .SO (g1_n_551), .C1
       (g1_inc_add_89_20_n_261));
  HADDX1 g1_inc_add_89_20_g429__5115(.A0 (g1_s_counter[10]), .B0
       (g1_inc_add_89_20_n_265), .SO (g1_n_552), .C1
       (g1_inc_add_89_20_n_263));
  HADDX1 g1_inc_add_89_20_g430__7482(.A0 (g1_s_counter[9]), .B0
       (g1_inc_add_89_20_n_267), .SO (g1_n_553), .C1
       (g1_inc_add_89_20_n_265));
  HADDX1 g1_inc_add_89_20_g431__4733(.A0 (g1_s_counter[8]), .B0
       (g1_inc_add_89_20_n_269), .SO (g1_n_554), .C1
       (g1_inc_add_89_20_n_267));
  HADDX1 g1_inc_add_89_20_g432__6161(.A0 (g1_s_counter[7]), .B0
       (g1_inc_add_89_20_n_271), .SO (g1_n_555), .C1
       (g1_inc_add_89_20_n_269));
  HADDX1 g1_inc_add_89_20_g433__9315(.A0 (g1_s_counter[6]), .B0
       (g1_inc_add_89_20_n_273), .SO (g1_n_556), .C1
       (g1_inc_add_89_20_n_271));
  HADDX1 g1_inc_add_89_20_g434__9945(.A0 (g1_s_counter[5]), .B0
       (g1_inc_add_89_20_n_275), .SO (g1_n_557), .C1
       (g1_inc_add_89_20_n_273));
  HADDX1 g1_inc_add_89_20_g435__2883(.A0 (g1_s_counter[4]), .B0
       (g1_inc_add_89_20_n_277), .SO (g1_n_558), .C1
       (g1_inc_add_89_20_n_275));
  HADDX1 g1_inc_add_89_20_g436__2346(.A0 (g1_s_counter[3]), .B0
       (g1_inc_add_89_20_n_279), .SO (g1_n_559), .C1
       (g1_inc_add_89_20_n_277));
  HADDX1 g1_inc_add_89_20_g437__1666(.A0 (g1_s_counter[2]), .B0
       (g1_inc_add_89_20_n_281), .SO (g1_n_560), .C1
       (g1_inc_add_89_20_n_279));
  HADDX1 g1_inc_add_89_20_g438__7410(.A0 (g1_s_counter[0]), .B0
       (g1_s_counter[1]), .SO (g1_n_561), .C1 (g1_inc_add_89_20_n_281));
  OA22X1 g1_gte_48_14_g734__6417(.IN1 (g1_gte_48_14_n_40), .IN2
       (g1_gte_48_14_n_65), .IN3 (g1_s_weight[3]), .IN4
       (g1_gte_48_14_n_8), .Q (g1_gte_48_14_n_66));
  OA22X1 g1_gte_48_14_g735__5477(.IN1 (g1_gte_48_14_n_38), .IN2
       (g1_gte_48_14_n_64), .IN3 (g1_s_weight[2]), .IN4
       (g1_gte_48_14_n_26), .Q (g1_gte_48_14_n_65));
  OA21X1 g1_gte_48_14_g736__2398(.IN1 (g1_s_weight[1]), .IN2
       (g1_gte_48_14_n_62), .IN3 (g1_gte_48_14_n_63), .Q
       (g1_gte_48_14_n_64));
  NAND2X1 g1_gte_48_14_g737__5107(.IN1 (g1_gte_48_14_n_46), .IN2
       (g1_s_counter[1]), .QN (g1_gte_48_14_n_63));
  NOR2X0 g1_gte_48_14_g738__6260(.IN1 (g1_gte_48_14_n_46), .IN2
       (g1_s_counter[1]), .QN (g1_gte_48_14_n_62));
  AND2X1 g1_gte_48_14_g759__4319(.IN1 (g1_gte_48_14_n_8), .IN2
       (g1_s_weight[3]), .Q (g1_gte_48_14_n_40));
  AND2X1 g1_gte_48_14_g761__8428(.IN1 (g1_gte_48_14_n_26), .IN2
       (g1_s_weight[2]), .Q (g1_gte_48_14_n_38));
  NAND2X1 g1_gte_48_14_g769__5526(.IN1 (g1_gte_48_14_n_14), .IN2
       (g1_s_weight[0]), .QN (g1_gte_48_14_n_46));
  INVX0 g1_gte_48_14_g786(.INP (g1_s_counter[0]), .ZN
       (g1_gte_48_14_n_14));
  OR2X1 g9215(.IN1 (g1_s_weight[4]), .IN2 (g1_gte_48_14_n_66), .Q
       (n_304));
  NOR4X0 g9216(.IN1 (g1_s_weight[31]), .IN2 (g1_s_weight[30]), .IN3
       (g1_s_weight[29]), .IN4 (n_306), .QN (n_305));
  OR4X1 g2(.IN1 (g1_s_weight[28]), .IN2 (g1_s_weight[27]), .IN3
       (g1_s_weight[26]), .IN4 (n_307), .Q (n_306));
  OR4X1 g9217(.IN1 (g1_s_weight[25]), .IN2 (g1_s_weight[24]), .IN3
       (g1_s_weight[23]), .IN4 (n_308), .Q (n_307));
  OR4X1 g9218(.IN1 (g1_s_weight[22]), .IN2 (g1_s_weight[21]), .IN3
       (g1_s_weight[20]), .IN4 (n_309), .Q (n_308));
  OR4X1 g9219(.IN1 (g1_s_weight[19]), .IN2 (g1_s_weight[18]), .IN3
       (g1_s_weight[17]), .IN4 (n_310), .Q (n_309));
  OR4X1 g9220(.IN1 (g1_s_weight[16]), .IN2 (g1_s_weight[15]), .IN3
       (g1_s_weight[14]), .IN4 (n_311), .Q (n_310));
  OR4X1 g9221(.IN1 (g1_s_weight[13]), .IN2 (g1_s_weight[12]), .IN3
       (g1_s_weight[11]), .IN4 (n_312), .Q (n_311));
  OR4X1 g9222(.IN1 (g1_s_weight[10]), .IN2 (g1_s_weight[9]), .IN3
       (g1_s_weight[8]), .IN4 (n_313), .Q (n_312));
  OR4X1 g9223(.IN1 (g1_s_weight[7]), .IN2 (g1_s_weight[6]), .IN3
       (g1_s_weight[5]), .IN4 (n_304), .Q (n_313));
  AOI21X1 g9224(.IN1 (n_314), .IN2 (n_95), .IN3 (n_16), .QN (n_315));
  NOR2X0 g3(.IN1 (g1_state[3]), .IN2 (grant1[0]), .QN (n_314));
endmodule

